import gradio as gr
import threading
import os
import socket

import uvicorn
from .api.fastapi_app import app as fastapi_app


_server_thread = None
_server_running = False


def _find_free_port(preferred: int = 8877) -> int:
    try:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", preferred))
            return preferred
    except OSError:
        with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
            s.bind(("127.0.0.1", 0))
            return s.getsockname()[1]


def start_fastapi_server(port: int | None = None) -> str:
    global _server_thread, _server_running
    if _server_running:
        return "API server already running."

    port = port or 8877
    port = _find_free_port(port)

    # Make URLs generated by integration default to this server
    os.environ["PYVIDEOTRANS_API_BASE_URL"] = f"http://127.0.0.1:{port}"

    def _run():
        config = uvicorn.Config(fastapi_app, host="127.0.0.1", port=port, log_level="info")
        server = uvicorn.Server(config)
        try:
            server.run()
        finally:
            # If server exits, mark as not running
            global _server_running
            _server_running = False

    _server_thread = threading.Thread(target=_run, daemon=True)
    _server_thread.start()
    _server_running = True
    return f"API server started at http://127.0.0.1:{port}"

def pyvideotrans_api_ui():
    gr.Markdown(
        """
    # Pyvideotrans api
    
    This is a template extension. Replace this content with your extension's functionality.
    
    To use it, simply modify this UI and add your custom logic.
    """
    )
    with gr.Row():
        port_in = gr.Number(value=8877, precision=0, label="API Port")
        start_btn = gr.Button("Start FastAPI server", variant="primary")
    status = gr.Markdown("API server not running.")

    def _on_start(p):
        try:
            msg = start_fastapi_server(int(p))
        except Exception as e:
            msg = f"Failed to start: {e}"
        return msg

    start_btn.click(fn=_on_start, inputs=[port_in], outputs=[status])


def extension__tts_generation_webui():
    pyvideotrans_api_ui()
    
    return {
        "package_name": "tts_webui_extension.pyvideotrans_api",
        "name": "Pyvideotrans api",
        "requirements": "git+https://github.com/rsxdalv/tts_webui_extension.pyvideotrans_api@main",
        "description": "A template extension for TTS Generation WebUI",
        "extension_type": "interface",
        "extension_class": "text-to-speech",
        "author": "Your Name",
        "extension_author": "rsxdalv",
        "license": "MIT",
        "website": "https://github.com/rsxdalv/tts_webui_extension.pyvideotrans_api",
        "extension_website": "https://github.com/rsxdalv/tts_webui_extension.pyvideotrans_api",
        "extension_platform_version": "0.0.1",
    }


if __name__ == "__main__":
    if "demo" in locals():
        locals()["demo"].close()
    with gr.Blocks() as demo:
        with gr.Tab("Pyvideotrans api", id="pyvideotrans_api"):
            pyvideotrans_api_ui()

    demo.launch(
        server_port=7772,  # Change this port if needed
    )
